### ISSUE TITLE
Switch aws global config to constructor

### ISSUE THREAD

**Issue by Eomm** [matrus2/fastify-dynamodb#1]
Hi,
as this issue describe https://github.com/aws/aws-sdk-js/issues/1276 this line:

https://github.com/matrus2/fastify-dynamodb/blob/a6ffe9ae441366adf31ada416a7f431541d95b57/index.js#L5

is breaking the encapsulation and cause some unexpected behaviour to a fastify server with two separate contexts with this plugin

**Comment by matrus2** [comment]
Fixed by https://github.com/matrus2/fastify-dynamodb/pull/2
